apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Maven pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Maven build
        uses: docker://maven:3-eclipse-temurin-17
        shell: sh
        run: |
          mvn clean verify -Dtest="*,!MySql*,!Postgres*"
  SonarQube:
    needs: build
    steps:
      - uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v1
        name: Run SonarQube scan
        kind: scan
  JFrog:
    needs: SonarQube
    steps:
      - name: Jfrog configure
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: mycbplatform.jfrog.io
          username: ${{ secrets.JFrog_username }}
          password: ${{ secrets.JFrog_password }}
      - name: Push image to the configured OCI Registry
        uses: cloudbees-io/kaniko@v1
        with:
          destination: maven-pet-clinic-libs-snapshot
         


     